---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mousetRap

<!-- badges: start -->
<!-- badges: end -->

## Installation

Install the development version of `mousetRap` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("martinasladek/mousetrap")
```

## Shiny App

To install the `shiny` R package for checking `mousetRap` output, visit the [GitHub page for `shinymousetRap`](https://github.com/martinasladek/shinymousetrap), or run: 

```{r eval = FALSE}
if(!require(mousetrap)){
  devtools::install_github("martinasladek/mousetrap")
}

devtools::install_github("martinasladek/shinymousetrap")
```


## Example

Loading `mousetRap`:

```{r example}
library(mousetrap)
```

To generate data, run: 

```{r cars}
mousetrap::get_data(cand_no = 12345)
```


